# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: select
    vstsFeed: my-vsts-feed

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: --configuration $(buildConfiguration)
  displayName: dotnet build $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs: 
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs: 
   command: publish
   publishWebProjects: True
   arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactsStagingDirectory)'
   zipAfterPublish: True
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureWebApp@1
  inputs:
   azureSubscription: 329721d5-deb1-4957-b038-ce28ff50bc4d
   appName: PipelineApp0418
   appType: webApp
   package: '$(System.DefaultWorkingDirectory)'

